language: php

services:
  - mysql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
 - DB=mysql

before_script:
  - mysql < database/clean.sql
  - mysql < database/exm_db_init.sql

script: phpunit --configuration phpunit.xml
