language: php

services:
  - mysql

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer global require 'phpunit/phpunit=4.3.*'

before_script:
  - phpenv config-add phpmods.ini
  - mysql -uroot < database/clean.sql
  - mysql -uroot < database/exm_db_init.sql
  - composer self-update
  - composer install

script:
  - phpunit --configuration phpunit.xml

notifications:
  - email: false
