language: php

services:
  - mysql

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - require --dev --no-update phpunit/phpunit ~5.1

before_script:
  - phpenv config-add phpmods.ini
  - mysql -uroot < database/clean.sql
  - mysql -uroot < database/exm_db_init.sql
  - composer self-update

script:
  - phpunit --configuration phpunit.xml

notifications:
  - email: false
