language: php

services:
  - mysql

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
<<<<<<< HEAD
  - mysql -uroot < database/clean.sql
  - mysql -uroot < database/exm_db_init.sql
=======
  - mysql < database/clean.sql
  - mysql < database/exm_db_init.sql
>>>>>>> 8c11b6ff7d88ed62942b4d949fc1be87f2161df3
  - composer self-update

script: 
  - phpunit --configuration phpunit.xml

notifications:
  - email: false
