language: php

services:
  - mysql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - mysql -uroot < database/clean.sql
  - mysql -uroot < database/exm_db_init.sql

script: phpunit --configuration phpunit.xml

notifications:
  email: false
